name: 'Get Package'
description: 'Install packages from OS package manager'
author: Wessel van Norel
inputs:
  brew:
    description: |
      Space-separated list of packages to install using brew install. Will
      only run if on OSX.
    required: false
  apt-get:
    description: |
      Space-separated list of packages to install using apt-get. Will
      only run if on linux.
    required: false
  snap:
    description: |
      Space-separated list of packages to install using snap. Will
      only run if on linux. Will only work if snap is installed.
    required: false
  linuxbrew:
    description: |
      Space-separated list of packages to install using brew on linux. Will
      only run if on linux. Will only work if brew is installed.
    required: false
branding:
  icon: arrow-down
  color: white
runs:
  using: 'node16'
  main: 'index.js'

